// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Ambient_Sound___Market = "Ambient Sound - Market",
  Ambient_Sound___Market_2 = "Ambient Sound - Market_2",
  Ambient_Sound___Water = "Ambient Sound - Water",
  Ambient_Sound___Water_2 = "Ambient Sound - Water_2",
  Ambient_Sound___Water_3 = "Ambient Sound - Water_3",
  Ambient_Sound___Water_4 = "Ambient Sound - Water_4",
  Ambient_Sound___Water_5 = "Ambient Sound - Water_5",
  BobOctorossPartB_V02_glb = "BobOctorossPartB_V02.glb",
  Box_Big = "Box Big",
  Dragon_glb = "Dragon.glb",
  Hidrant = "Hidrant",
  MedievalPlaza_glb = "MedievalPlaza.glb",
  Point_light = "Point light",
  Point_light_2 = "Point light_2",
  Table_2 = "Table 2",
  berry1 = "berry1",
  berry2 = "berry2",
  berry3 = "berry3",
  berry4 = "berry4",
  berry5 = "berry5",
  berry6 = "berry6",
  berry7 = "berry7",
  berry8 = "berry8",
  berry9 = "berry9",
  calis = "calis",
  calis2 = "calis2",
  calis3 = "calis3",
  calis4 = "calis4",
  catguy = "catguy",
  kimkim1 = "kimkim1",
  kimkim2 = "kimkim2",
  kimkim3 = "kimkim3",
  kimkim4 = "kimkim4",
  vine1 = "vine1",
  vine2 = "vine2",
  vine3 = "vine3",
  vine4 = "vine4",
  vine5 = "vine5",
  vine6 = "vine6",
  vine7 = "vine7",
  vine8 = "vine8",
} 
